package com.example.demo.enums;
public enum TaskEventType {
    STATUS_PROGRESSED, //BİR SONRAKİ COLUMNA MOVE TO ORDER INDEX ARTAR
    STATUS_ROLLBACK, //BİR ÖNCEK COLUMNA MOVE TO ORDER INDEX AZALIR
    TASK_COMPLETED,

    ASSIGNEE_CHANGED, //İLK KEZ ASSIGNED OLDUĞUNDA

    MOVED_TO_LIST //AMA LOCATİONS LAZIM
}
