spring:
  application:
    name: demo
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/clıckup_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Postgres123!}

  #jackson:
   # property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: create #validate ve migration flyway yönetilmeli
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

clickup:
  api:
    base-url: "https://api.clickup.com/api/v2"
    token: "pk_240227764_3TEOOT6VGGD8KEFT28BC18757K0NOEPW"
    team_id: "team_id"
    endpoints:
      teams: "/team"
      spaces: "/team/{teamId}/space"
      folders: "/space/{spaceId}/folder"
      #folder_list: "/folder/{folderId}/list"
      space_list: "/space/{spaceId}/list"
      tasks: "/team/{teamId}/task"
