ALTER TABLE tasks ADD COLUMN IF NOT EXISTS priority VARCHAR(50);
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS blocked_by_task_id VARCHAR(255);

ALTER TABLE task_events DROP COLUMN IF EXISTS assignee_id;
ALTER TABLE task_events ADD COLUMN IF NOT EXISTS from_assignee BIGINT;
ALTER TABLE task_events ADD COLUMN IF NOT EXISTS to_assignee BIGINT;